import { StyleSheet } from "react-native";
import { Cores } from "./cores";

export const estilosComuns = StyleSheet.create({
  conteiner: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 25,
    backgroundColor: Cores.fundo,
  },
  conteinerModal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.35)",
  },
  titulo: {
    fontSize: 26,
    fontWeight: "bold",
    marginTop: 10,
    marginBottom: 20,
    color: Cores.texto,
  },
  subtitulo: {
    fontSize: 18,
    color: Cores.textoClaro,
    marginBottom: 40,
  },
  escolha: {
    width: "85%",
    height: 50,
    backgroundColor: Cores.branco,
    borderColor: Cores.borda,
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 20,
    fontSize: 16,
  },
  esqueciSenha: {
    color: Cores.primario,
    fontWeight: "bold",
    marginTop: 15,
    fontSize: 16,
  },
  rodape: {
    marginTop: 30,
    flexDirection: "row",
  },
  linkRodape: {
    color: Cores.primario,
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 5,
  },
  inputEntrar: {
    width: "100%",
    height: 50,
    borderColor: Cores.borda,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 20,
    backgroundColor: Cores.branco,
    fontSize: 16,
    color: Cores.texto,
    shadowColor: Cores.sombra,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  inputPrincipalAdm: {
    width: "100%",
    height: 40,
    borderColor: Cores.borda,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 15,
    fontSize: 16,
    backgroundColor: Cores.branco,
    color: Cores.texto,
  },
  input: {
    width: "85%",
    height: 50,
    borderColor: Cores.borda,
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    backgroundColor: Cores.branco,
    paddingHorizontal: 15,
    alignSelf: "center",
  },
  inputSenha: {
    width: "100%",
    height: 50,
    borderColor: Cores.borda,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 20,
    backgroundColor: Cores.branco,
    fontSize: 16,
    color: Cores.texto,
  },
  inputRegistrar: {
    width: "100%",
    height: 50,
    borderColor: Cores.borda,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 20,
    backgroundColor: Cores.branco,
    fontSize: 16,
    color: Cores.texto,
    shadowColor: Cores.sombra,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  botaoCancelar: {
    width: "100%",
    height: 50,
    backgroundColor: Cores.alerta,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    marginTop: 10,
  },
  botao: {
    width: "85%",
    height: 50,
    backgroundColor: Cores.primario,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    marginTop: 15,
    alignSelf: "center",
  },
  botaoSenha: {
    width: "85%",
    height: 50,
    backgroundColor: Cores.primario,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    marginTop: 10,
  },
  botaoRegistrar: {
    width: "100%",
    height: 50,
    backgroundColor: Cores.primario,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    marginTop: 10,
    shadowColor: Cores.sombra,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  botaoLogin: {
    width: "85%",
    height: 50,
    backgroundColor: Cores.primario,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    marginTop: 10,
    shadowColor: Cores.sombra,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  botaoSair: {
    backgroundColor: Cores.erro,
    marginTop: 20,
  },
  scrollContainer: {
    flexGrow: 1,
    padding: 16,
  },
  listaAgendamento: {
    width: "100%",
    marginTop: 20,
  },
  listaTitulo: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 15,
    color: Cores.texto,
  },
  itemAgendamento: {
    backgroundColor: Cores.branco,
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
    borderColor: Cores.borda,
    borderWidth: 1,
    shadowColor: Cores.sombra,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  textoAgendamento: {
    fontSize: 16,
    color: Cores.texto,
    marginBottom: 5,
  },
  textoNegrito: {
    fontWeight: "bold",
    color: Cores.primario,
  },
  textoSemAgendamentos: {
    fontSize: 16,
    color: Cores.textoClaro,
    marginTop: 20,
    textAlign: "center",
  },
  textoRodape: {
    color: Cores.texto,
    fontSize: 16,
  },
  textoData: {
    fontSize: 18,
    color: Cores.texto,
  },
  textoBotao: {
    color: Cores.branco,
    fontSize: 18,
    fontWeight: "bold",
    alignItems: "center",
    justifyContent: "center",
  },
  textoBemVindo: {
    fontSize: 22,
    color: Cores.texto,
    marginBottom: 30,
    textAlign: "center",
    fontWeight: "600",
    marginTop: 20,
  },
  formularioServico: {
    width: "100%",
    padding: 20,
    backgroundColor: Cores.branco,
    borderRadius: 12,
    marginTop: 20,
    borderColor: Cores.borda,
    borderWidth: 1,
  },
  formularioTitulo: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 15,
    color: Cores.texto,
    alignSelf: "center",
  },
  conteudoModal: {
    width: "80%",
    padding: 20,
    backgroundColor: Cores.branco,
    borderRadius: 12,
    shadowColor: Cores.sombra,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
  },
});
