import { StyleSheet } from "react-native";
import { Cores } from "./cores";

export const estilosComuns = StyleSheet.create({
  escolhaDataHoraAgendamento: {
    width: "85%",
    height: 50,
    backgroundColor: Cores.branco,
    borderColor: Cores.borda,
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 20,
    fontSize: 16,
  },
  botao: {
    width: "85%",
    height: 50,
    backgroundColor: Cores.primario,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    marginTop: 15,
    alignSelf: "center",
  },
  botaoLogout: {
    backgroundColor: Cores.erro,
    marginTop: 20,
  },
  scrollConteiner: {
    flexGrow: 1,
    padding: 16,
  },
  listaAgendamentoCliente: {
    width: "100%",
    marginTop: 20,
  },
  itemAgendamento: {
    backgroundColor: Cores.branco,
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
    borderColor: Cores.borda,
    borderWidth: 1,
    shadowColor: Cores.sombra,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  textoAgendamento: {
    fontSize: 16,
    color: Cores.texto,
    marginBottom: 5,
  },
  textoNegrito: {
    fontWeight: "bold",
    color: Cores.primario,
  },
  textoSemAgendamentos: {
    fontSize: 16,
    color: Cores.textoClaro,
    marginTop: 20,
    textAlign: "center",
  },
  textoDataAgendamento: {
    fontSize: 18,
    color: Cores.texto,
  },
  textoComum: {
    fontSize: 22,
    color: Cores.texto,
    marginBottom: 30,
    textAlign: "center",
    fontWeight: "600",
    marginTop: 20,
  },
  conteiner: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 25,
    backgroundColor: Cores.branco,
  },
  titulo: {
    fontSize: 28,
    fontWeight: "bold",
    marginTop: 10,
    marginBottom: 10,
    color: Cores.primario,
  },
  subtitulo: {
    fontSize: 18,
    color: Cores.textoClaro,
    marginBottom: 30,
  },
  input: {
    width: "100%",
    height: 50,
    borderBottomWidth: 1,
    borderColor: Cores.borda,
    backgroundColor: "transparent",
    paddingHorizontal: 0,
    marginBottom: 25,
    fontSize: 16,
    color: Cores.texto,
  },
  botaoLogin: {
    width: "100%",
    height: 52,
    backgroundColor: Cores.primario,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    marginTop: 20,
    shadowColor: Cores.sombra,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  textoBotao: {
    color: Cores.branco,
    fontSize: 18,
    fontWeight: "bold",
  },
  esqueciSenha: {
    color: Cores.primario,
    fontWeight: "bold",
    marginTop: 20,
    fontSize: 16,
  },
  rodape: {
    marginTop: 30,
    flexDirection: "row",
  },
  textoRodape: {
    color: Cores.texto,
    fontSize: 16,
  },
  linkRodape: {
    color: Cores.primario,
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 5,
  },
  inputDataHoraAgendamento: {
    width: "85%",
    borderBottomWidth: 1,
    borderColor: Cores.borda,
    paddingVertical: 12,
    marginBottom: 20,
    justifyContent: "center",
  },
  textoBotaoModalRecuperarSenha: {
    color: '#fff',
    fontWeight: 'bold',
  },
  fecharModalRecuperarSenha: {
    color: Cores.textoClaro,
    marginTop: 10,
    fontSize: 16,
  },
  fundoModalAgendamentosCliente: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  conteinerModalAgendamentosCliente: {
    width: "90%",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 20,
    maxHeight: "80%",
  },
  tituloModalAgendamento: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  scrollModalAgendamentos: {
    width: "100%",
  },
  conteudoModalAgendamento: {
    paddingBottom: 20,
  },
  conteinerModalRecuperarSenha: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  conteudoModalRecuperarSenha: {
    width: '80%',
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    alignItems: 'center',
  },
  tituloModalRecuperarSenha: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  inputModalRecuperarSenha: {
    width: '100%',
    height: 50,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    paddingLeft: 10,
    marginBottom: 20,
  },
  botaoModalRecuperarSenha: {
    width: '100%',
    backgroundColor: Cores.primario,
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  conteinerModalNovoServico: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.35)",
  },
  modalTituloNovoServico: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 15,
    color: Cores.texto,
    alignSelf: "center",
  },
  conteudoModalNovoServico: {
    width: "80%",
    padding: 20,
    backgroundColor: Cores.branco,
    borderRadius: 12,
    shadowColor: Cores.sombra,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
  },
});
